### ISSUE TITLE
Not using IPOPT in bnb

### ISSUE THREAD

**Issue by kibaekkim** [ashutoshmahajan/minotaur#2]
I would like to use binary ``bnb`` with option ``--nlp_engine IPOPT``. But, MINOTAUR does not use ``Ipopt``.

**Comment by meenarli** [comment]
Minotaur has the option of using IPOPT for solving MINLPs and it seems working. The option is turned on the same way you have mentioned. Could you please write a little more about how exactly are you using it and what error are you getting.

**Comment by ashutoshmahajan** [comment]
Try this: 
bnb --qp_engine None --nlp_engine IPOPT

By default, if the relaxation is a QP, it will try to use a QP solver (BQPD). Hope it helps. Do let us know so that we can close this issue.

**Comment by kibaekkim** [comment]
@ashutoshmahajan Yes. That works! Thanks!
